---
kubectl_http_proxy: ''
kubectl_https_proxy: ''

fileserver_http_proxy:  ''
fileserver_https_proxy: ''

docker_repo_cache_http_proxy: ''
docker_repo_cache_https_proxy: ''

namespaces:
  - kube-system
  - k8sdc-infra
  - k8sdc-development
  - k8sdc-productivity

solutions:
  cs1_cluster_services:


  cm1_cluster_management:
    enable:     yes
    namespace:  kube-system
    role_tasks: no
    hostnames:
      kube_dashboard: dashboard.k8sdc.io

  dbs1_distributed_block_storage:
    enable:     yes
    namespace:  k8sdc-system
    role_tasks: yes
    mon_hosts:
      - hostname: node1.vb.k8sdc.io
      - hostname: node2.vb.k8sdc.io
      - hostname: node3.vb.k8sdc.io
    osd_hosts:
      - hostname:   node1.vb.k8sdc.io
        count_256m: 40
      - hostname:   node2.vb.k8sdc.io
        count_256m: 40
      - hostname:   node3.vb.k8sdc.io
        count_256m: 40

  im1_identity_management:
    enable:     yes
    namespace:  k8sdc-system
    role_tasks: no
    hostnames: 
      keycloack: keycloak.k8sdc.io

  hrp1_https_reverse_proxy:
    enable:     yes
    namespace:  k8sdc-system
    role_tasks: no
    keepalived: yes
    vip:        10.0.0.100

  m1_metrics:
    enable:     yes
    namespace:  k8sdc-system
    role_tasks: no
    hostnames:
      prometheus: prometheus.k8sdc.io
      grafana:    grafana.k8sdc.io 

  l1_logging:
    enable:     yes
    namespace:  k8sdc-system
    role_tasks: no
    hostnames:
      kibana:         kibana.k8sdc.io
      kafka_admin:    kafka.k8sdc.io
      logstash_admin: logstash.k8sdc.io
