---
# Generate a private key and certificate

- debug:
    var: cn
- debug:
    var: dns_values
- debug:
    var: ip_values


- name: Create certificate temp directory
  file:
    path:  /tmp/k8sdc-ca/
    state: directory
    mode:  0750

- name: Create openssl.conf
  template:
    src: "{{ role_path }}/../k8sdc-ca/templates/openssl.conf.j2"
    dest: /tmp/k8sdc-ca/openssl.conf

# generate key

# generate csr

# generate cert

- name: Set key fact
  set_fact:
    "{{ cert_name }}_key": "{{ cert_name }}"

- name: Set certificate fact
  set_fact:
    "{{ cert_name }}_cert": "{{ cert_name }}"

- name: Remove certificate temp directory
  file:
    path:  /tmp/k8sdc-ca/
    state: absent
