---
- name: Test distribution
  hosts:
    - k8sdc-master
    - k8sdc-nodes
    - etcd
    - fileserver
  tasks:
    - assert:
        that: ansible_os_family == "RedHat"
  tags: confirm_redhat

- name: Configure common components
  hosts:
    - k8sdc-master
    - k8sdc-nodes
    - etcd
    - fileserver
  sudo:  yes
  roles:
    - common
  tags: configure_common

- name: Configure Etcd
  hosts: 
    - etcd
  sudo:  yes
  roles:
    - etcd
  tags: configure_etcd

- name: Configure Flannel
  hosts: 
    - k8sdc-master
    - k8sdc-nodes
  sudo:  yes
  roles:
    - flannel
  tags: configure_flannel

- name: Configure Docker
  hosts: 
    - k8sdc-master
    - k8sdc-nodes
  sudo:  yes
  roles:
    - docker
  tags: configure_docker

- name: Configure Kubernetes
  hosts: 
    - k8sdc-master
    - k8sdc-nodes
  sudo:  yes
  roles:
    - kubernetes
  tags: configure_kubernetes

# - name:  Configure Network Filesystem
#   hosts: 
#     - k8sdc-master
#     - k8sdc-nodes
#   sudo:  yes
#   roles:
#     - { role: nfs, when: install_nfs }
#   tags: configure_nw_filesystem

# - name: Configure Cluster Services
#   hosts: k8sdc-master
#   sudo: yes
#   roles:
#     - services-cluster
#   tags: configure_services_cluster

# - name: Configure Infrastucture Services
#   hosts: k8sdc-master
#   sudo: yes
#   roles:
#     - services-infrastructure
#   tags: configure_services_infrastructure

# - name: Configure Development Services
#   hosts: k8sdc-master
#   sudo: yes
#   roles:
#     - services-development
#   tags: configure_services_development

# - name: Configure Productivity Services
#   hosts: k8sdc-master
#   sudo: yes
#   roles:
#     - services-productivity
#   tags: configure_services_productivity

