---
# Configure Kubernetes masters
- name: Create certs, tokens and users directories
  file:
    path: /etc/kubernetes/{{ item }}
    state: directory
    owner: kube
    group: kube
    mode:  0770
  with_items:
    - certs
    - tokens
    - users


# Kubernetes master binaries
- name: Stop master services
  service:
    name:  "{{ item }}"
    state: stopped
  ignore_errors: true
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
  tags:
    - k8s_binaries
    - k8s_master_binaries

- name: Fetch Kubernetes binaries from fileserver
  command: >
      scp -o StrictHostKeyChecking=no
          -i /home/{{ admin_user }}/.ssh/{{ private_key | basename }} 
          {{ admin_user }}@{{ fileserver }}:/{{ download_dir }}/kubernetes_binaries_{{ kubernetes_version }}/{{ item }}
          /usr/bin/{{ item }}
  notify:
    - Restart master daemons
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubectl
  tags:
    - k8s_binaries
    - k8s_master_binaries

- name: Configure master binary permissions
  file:
    path:  /usr/bin/{{ item }}
    state: file
    mode:  0755
    owner: kube
    group: kube
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubectl
  tags:
    - k8s_binaries
    - k8s_master_binaries


# Kubernetes master config
- name: Copy master config file
  template:
    src:  config/config.j2
    dest: /etc/kubernetes/config
  notify:
    - Reload Systemd
    - Restart master daemons
  tags:
    - k8s_master_config

- name: Configure master config file permissions
  file:
    path:  /etc/kubernetes/config
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:
    - k8s_master_config    


# Kubernetes kube-apiserver config
- name: Copy kube-apiserver service file
  copy:
    src:  services/kube-apiserver.service
    dest: /usr/lib/systemd/system/kube-apiserver.service
  notify:
    - Reload Systemd
    - Restart kube-apiserver
  tags:
    - k8s_kube_apiserver_config

- name: Copy kube-apiserver config file
  template:
    src:  config/kube-apiserver.j2
    dest: /etc/kubernetes/kube-apiserver
  notify:
    - Reload Systemd
    - Restart kube-apiserver
  tags:
    - k8s_kube_apiserver_config

- name: Configure kube-apiserver config file permissions
  file:
    path:  /etc/kubernetes/kube-apiserver
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:   
    - k8s_kube_apiserver_config

- name: Enable kube-apiserver service
  service:
    name:    kube-apiserver
    enabled: yes
  tags:
    - k8s_kube_apiserver_config


# Kubernetes kube-scheduler config
- name: Copy kube-scheduler service file
  copy:
    src:  services/kube-scheduler.service
    dest: /usr/lib/systemd/system/kube-scheduler.service
  notify:
    - Reload Systemd
    - Restart kube-scheduler
  tags:
    - k8s_kube_scheduler_config

- name: Copy kube-scheduler config file
  template:
    src:  config/kube-scheduler.j2
    dest: /etc/kubernetes/kube-scheduler
  notify:
    - Reload Systemd
    - Restart kube-scheduler
  tags:
    - k8s_kube_scheduler_config

- name: Configure kube-scheduler config file permissions
  file:
    path:  /etc/kubernetes/kube-scheduler
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:   
    - k8s_kube_scheduler_config

- name: Enable kube-scheduler service
  service:
    name:    kube-scheduler
    enabled: yes
  tags:
    - k8s_kube_scheduler_config


# Kubernetes kube-controller-manager config
- name: Copy kube-controller-manager service file
  copy:
    src:  services/kube-controller-manager.service
    dest: /usr/lib/systemd/system/kube-controller-manager.service
  notify:
    - Reload Systemd
    - Restart kube-controller-manager
  tags:
    - k8s_kube_controller_manager_config

- name: Copy kube-controller-manager config file
  template:
    src:  config/kube-controller-manager.j2
    dest: /etc/kubernetes/kube-controller-manager
  notify:
    - Reload Systemd
    - Restart kube-controller-manager
  tags:
    - k8s_kube_controller_manager_config

- name: Configure kube-controller-manager config file permissions
  file:
    path:  /etc/kubernetes/kube-controller-manager
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:   
    - k8s_kube_controller_manager_config

- name: Enable kube-controller-manager service
  service:
    name:    kube-controller-manager
    enabled: yes
  tags:
    - k8s_kube_controller_manager_config





# - name: Include security configuration
#   include: security.yaml
#   tags: security



# - name: Configure firewalld ports for Kubernetes
#   firewalld: 
#     port:      "{{ item }}/tcp"
#     permanent: yes 
#     state:     enabled
#     immediate: yes
#   with_items:
#     - 8080
#   when: use_firewalld


