---
- name: Stop node services
  service:
    name:  "{{ item }}"
    state: stopped
  ignore_errors: true
  with_items:
    - kubelet
    - kube-proxy

- name: Copy node binaries
  command: cp /{{ download_dir }}/kubernetes/server/bin/{{ item }} /usr/bin/
  with_items:
    - kubelet
    - kube-proxy
    - kubectl

- name: Configure node binary permissions
  file:
    path:  /usr/bin/{{ item }}
    state: file
    mode:  0755
    owner: kube
    group: kube
  with_items:
    - kubelet
    - kube-proxy
    - kubectl


# Configure node
- name: Copy node config files
  template:
    src: config.j2
    dest: /etc/kubernetes/config
  notify:
    - Reload Systemd
    - Restart node daemons
  tags:
    - configure_kubernetes
    - configure_node

- name: Configure node config file permissions
  file:
    path:  /etc/kubernetes/config
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:
    - configure_kubernetes
    - configure_node


# Configure kubelet
- name: Copy kubelet service file
  copy:
    src: kubelet.service
    dest: /usr/lib/systemd/system/kubelet.service
  notify:
    - Reload Systemd
    - Restart kubelet
  tags:
    - configure_kubernetes
    - configure_node
    - configure_kubelet

- name: Copy kubelet config file
  template:
    src: kubelet.j2
    dest: /etc/kubernetes/kubelet
  notify:
    - Reload Systemd
    - Restart kubelet
  tags:
    - configure_kubernetes
    - configure_node
    - configure_kubelet

- name: Configure kubelet config file permissions
  file:
    path:  /etc/kubernetes/kubelet
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:   
    - configure_kubernetes
    - configure_node
    - configure_kubelet


# Configure kube-proxy
- name: Copy kube-proxy service file
  copy:
    src: kube-proxy.service
    dest: /usr/lib/systemd/system/kube-proxy.service
  notify:
    - Reload Systemd
    - Restart kube-proxy
  tags:
    - configure_kubernetes
    - configure_node
    - configure_kube_proxy

- name: Copy kube-proxy config file
  template:
    src: kube-proxy.j2
    dest: /etc/kubernetes/kube-proxy
  notify:
    - Reload Systemd
    - Restart kube-proxy
  tags:
    - configure_kubernetes
    - configure_node
    - configure_kube_proxy

- name: Configure kube-proxy config file permissions
  file:
    path:  /etc/kubernetes/kube-proxy
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:   
    - configure_kubernetes
    - configure_node
    - configure_kube_proxy



- name: Create certs and manifest directories
  file:
    path: /etc/kubernetes/{{ item }}
    state: directory
    owner: kube
    group: kube
    mode:  0770
  with_items:
    - certs
    - manifest
  tags: security

- name: Create CA certificate
  copy: 
    content: "{{ kube_ca_cert }}" 
    dest:    /etc/kubernetes/certs/ca.crt
    group:   kube
    owner:   kube
    mode:    0440
  tags: security

- name: Get the node token values
  slurp:
    src: "/etc/kubernetes/tokens/{{ item }}-{{ inventory_hostname }}.token"
  with_items:
    - "system:kubelet"
    - "system:proxy"
  register: tokens
  delegate_to: "{{ groups['kub-master'][0] }}"
  tags: security

- name: Set token facts
  set_fact:
    kubelet_token: "{{ tokens.results[0].content|b64decode }}"
    proxy_token: "{{ tokens.results[1].content|b64decode }}"
  tags: security

- name: write the kubecfg (auth) file for kubelet
  template: 
    src:  kubelet.kubeconfig.j2 
    dest: /etc/kubernetes/kubelet.kubeconfig
    owner: kube
    group: kube
  notify:
    - Restart kubelet
  tags: security

- name: write the kubecfg (auth) file for kube-proxy
  template: 
    src:  proxy.kubeconfig.j2 
    dest: /etc/kubernetes/proxy.kubeconfig
    owner: kube
    group: kube
  notify:
    - Restart kube-proxy
  tags: security

- name: Create /var/lib/kubelet/
  file:
    path: /var/lib/kubelet/
    state: directory
    owner: kube
    group: kube
    mode:  0755

- name: Reload Systemd
  command: systemctl daemon-reload

- name: Enable and start node services
  service:
    name:    "{{ item }}"
    enabled: yes
    state:   started
  ignore_errors: yes
  with_items:
    - kubelet
    - kube-proxy

# - name: Configure firewalld ports for etcd
#   firewalld: 
#     port:      "{{ item }}/tcp"
#     permanent: yes 
#     state:     enabled
#     immediate: yes
#   with_items:
#     - 2379
#     - 2380
#   when: use_firewalld


