---
# Kubernetes node binaries
- name: Stop node services
  service:
    name:  "{{ item }}"
    state: stopped
  ignore_errors: true
  with_items:
    - kubelet
    - kube-proxy
  tags:
    - k8s_binaries
    - k8s_node_binaries

- name: Fetch Kubernetes binaries from fileserver
  command: scp -o StrictHostKeyChecking=no \
           -i /home/{{ admin_user }}/.ssh/{{ private_key | basename }} \
           {{ admin_user }}@{{ fileserver }}:/{{ download_dir }}/kubernetes_binaries_{{ kubernetes_version }}/{{ item }} \
           /usr/bin/{{ item }}
  notify:
    - Restart node daemons
  with_items:
    - kubelet
    - kube-proxy
    - kubectl
  tags:
    - k8s_binaries
    - k8s_node_binaries

- name: Configure node binary permissions
  file:
    path:  /usr/bin/{{ item }}
    state: file
    mode:  0755
    owner: kube
    group: kube
  with_items:
    - kubelet
    - kube-proxy
    - kubectl
  tags:
    - k8s_binaries
    - k8s_node_binaries

- name: Create /var/lib/kubelet/
  file:
    path: /var/lib/kubelet/
    state: directory
    owner: kube
    group: kube
    mode:  0755
  tags:
    - k8s_binaries
    - k8s_node_binaries


# Kubernetes node config
- name: Copy node config files
  template:
    src: config.j2
    dest: /etc/kubernetes/config
  notify:
    - Reload Systemd
    - Restart node daemons
  tags:
    - k8s_node_config

- name: Configure node config file permissions
  file:
    path:  /etc/kubernetes/config
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:
    - k8s_node_config


# Kubernetes kubelet config
- name: Copy kubelet service file
  copy:
    src: kubelet.service
    dest: /usr/lib/systemd/system/kubelet.service
  notify:
    - Reload Systemd
    - Restart kubelet
  tags:
    - k8s_kubelet_config

- name: Enable kubelet service
  service:
    name:    kubelet
    enabled: yes
  tags:
    - k8s_kubelet_config

- name: Copy kubelet config file
  template:
    src: kubelet.j2
    dest: /etc/kubernetes/kubelet
  notify:
    - Reload Systemd
    - Restart kubelet
  tags:
    - k8s_kubelet_config

- name: Configure kubelet config file permissions
  file:
    path:  /etc/kubernetes/kubelet
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:   
    - k8s_kubelet_config


# Kubernetes kube-proxy config
- name: Copy kube-proxy service file
  copy:
    src: kube-proxy.service
    dest: /usr/lib/systemd/system/kube-proxy.service
  notify:
    - Reload Systemd
    - Restart kube-proxy
  tags:
    - k8s_kube_proxy_config

- name: Enable kube-proxy service
  service:
    name:    kube-proxy
    enabled: yes
  tags:
    - k8s_kube_proxy_config

- name: Copy kube-proxy config file
  template:
    src: kube-proxy.j2
    dest: /etc/kubernetes/kube-proxy
  notify:
    - Reload Systemd
    - Restart kube-proxy
  tags:
    - k8s_kube_proxy_config

- name: Configure kube-proxy config file permissions
  file:
    path:  /etc/kubernetes/kube-proxy
    state: file
    mode:  0644
    owner: kube
    group: kube
  tags:   
    - k8s_kube_proxy_config


# Kubernetes node security
- name: Read the CA certificate from a Kubernetes master
  slurp:
    src: "/etc/kubernetes/certs/ca.crt"
  register: ca_cert
  delegate_to: "{{ groups['k8sdc-master'][0] }}"
  run_once: yes
  tags:
    - k8s_security
    - k8s_node_security

- name: Decode the CA certificate and register it as a fact
  set_fact:
    kube_ca_cert: "{{ ca_cert.content|b64decode }}"
  tags:
    - k8s_security
    - k8s_node_security

- name: Create certs directory
  file:
    path: /etc/kubernetes/certs/
    state: directory
    owner: kube
    group: kube
    mode:  0770
  tags:
    - k8s_security
    - k8s_node_security

- name: Create CA certificate
  copy: 
    content: "{{ kube_ca_cert }}" 
    dest:    /etc/kubernetes/certs/ca.crt
    group:   kube
    owner:   kube
    mode:    0440
  tags:
    - k8s_security
    - k8s_node_security

- name: Get the kubelet and kube-proxy tokens from a Kubernetes master
  slurp:
    src: "/etc/kubernetes/tokens/{{ item }}-{{ inventory_hostname }}.token"
  with_items:
    - "system:kubelet"
    - "system:proxy"
  register: tokens
  delegate_to: "{{ groups['k8sdc-master'][0] }}"
  tags:
    - k8s_security
    - k8s_node_security

- name: Set token facts
  set_fact:
    kubelet_token: "{{ tokens.results[0].content|b64decode }}"
    proxy_token: "{{ tokens.results[1].content|b64decode }}"
  tags:
    - k8s_security
    - k8s_node_security

- name: write the kubecfg (auth) file for kubelet
  template: 
    src:  kubelet.kubeconfig.j2 
    dest: /etc/kubernetes/kubelet.kubeconfig
    owner: kube
    group: kube
  notify:
    - Restart kubelet
  tags:
    - k8s_security
    - k8s_node_security

- name: write the kubecfg (auth) file for kube-proxy
  template: 
    src:  proxy.kubeconfig.j2 
    dest: /etc/kubernetes/proxy.kubeconfig
    owner: kube
    group: kube
  notify:
    - Restart kube-proxy
  tags:
    - k8s_security
    - k8s_node_security


# # Kubernetes node firewalld
# - name: Configure firewalld
#   firewalld: 
#     port:      "{{ item }}/tcp"
#     permanent: yes 
#     state:     enabled
#     immediate: yes
#   with_items:
#     - 2379
#     - 2380
#   when: use_firewalld


